---
- name: Install and configure GitLab Runner
  hosts: worker
  tasks:
    - name: Add GitLab Runner repository
      apt_repository:
        repo: 'deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ focal main'
        state: present
    - name: Add GitLab Runner GPG key
      apt_key:
        url: 'https://packages.gitlab.com/gpg.key'
        state: present