---
- name: Install and configure GitLab Runner
  hosts: worker
  vars_files:
    - cred.yml
  tasks:
    - name: Register GitLab Runner
      command: >
        gitlab-runner register --non-interactive --url '{{ gitlab_runner_url }}' 
        --registration-token '{{ gitlab_registration_token }}' 
        --description '{{ runner_description }}' 
        --executor '{{ runner_executor }}' 
        --tag-list '{{ runner_tags }}' 
        --run-untagged='true' 
        --locked='false'
      register: register_output
    - debug:
        var: register_output.stdout