---
- name: Install and configure GitLab Runner
  hosts: 192.168.0.33
  vars_files:
    - dependencies.yml

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - "{{ dependencies }}"
        state: present